name: Release Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # required to create a release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Publish
        run: dotnet publish -c Release -r win-x64 --self-contained false -o ./publish

      - name: Set ZIP filename
        id: zipname
        run: echo "ZIPNAME=ChatBot-${GITHUB_REF_NAME}.zip" >> $GITHUB_ENV

      - name: Zip output
        run: cd publish && zip -r ../$ZIPNAME .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIPNAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
